PACKAGE_NAME="ov8865-fix"
PACKAGE_VERSION="1.1"

BUILT_MODULE_NAME[0]="ov8865"
DEST_MODULE_NAME[0]="ov8865"
DEST_MODULE_LOCATION[0]="/updates/dkms"

MAKE[0]="make KDIR=${kernel_source_dir} KVER=${kernelver}"
CLEAN="make clean KDIR=${kernel_source_dir} KVER=${kernelver}"

AUTOINSTALL="yes"
