PACKAGE_NAME="int3472-tps68470-fix"
PACKAGE_VERSION="1.0"
BUILT_MODULE_NAME[0]="intel_skl_int3472_tps68470"
DEST_MODULE_NAME[0]="intel_skl_int3472_tps68470"
DEST_MODULE_LOCATION[0]="/updates/dkms"
MAKE[0]="make KDIR=${kernel_source_dir} KVER=${kernelver}"
CLEAN="make clean KDIR=${kernel_source_dir} KVER=${kernelver}"
AUTOINSTALL="yes"
